(()=>{'use strict';const article=document.querySelector('.doc');if(!article)return;
article.querySelectorAll('math[display="block"]').forEach(m=>{if(m.closest('.math.display'))return;const w=document.createElement('div');w.className='math display';const p=m.parentElement;if(p.tagName==='P'&&p.children.length===1&&!p.textContent.replace(m.textContent,'').trim()){p.replaceWith(w)}else{m.before(w)}w.append(m)});
article.querySelectorAll('table').forEach(t=>{const w=document.createElement('div');w.className='table-wrap';t.before(w);w.append(t)});
const toc=document.querySelector('#page-toc');const links=new Map();article.querySelectorAll('h2,h3').forEach((h,i)=>{if(!h.id)h.id='section-'+i;if(!toc)return;const a=document.createElement('a');a.textContent=h.textContent;a.href='#'+h.id;if(h.tagName==='H3')a.className='level3';toc.append(a);links.set(h.id,a)});
if('IntersectionObserver'in window){new IntersectionObserver(es=>{es.filter(e=>e.isIntersecting).forEach(e=>{links.forEach(a=>a.classList.remove('active'));links.get(e.target.id)?.classList.add('active')})},{rootMargin:'-12% 0px -70% 0px'}).observe(article.querySelector('h2')||article);const o=new IntersectionObserver(es=>{const active=es.find(e=>e.isIntersecting);if(active){links.forEach(a=>a.classList.remove('active'));links.get(active.target.id)?.classList.add('active')}},{rootMargin:'-10% 0px -70% 0px'});article.querySelectorAll('h2,h3').forEach(h=>o.observe(h))}
const dialog=document.createElement('dialog');dialog.className='zoom-dialog';dialog.setAttribute('aria-label','原图查看器');dialog.innerHTML='<div class="zoom-toolbar"><span class="zoom-caption"></span><button data-action="out" aria-label="缩小">−</button><span class="zoom-level"></span><button data-action="in" aria-label="放大">＋</button><button data-action="fit">适应</button><button data-action="actual">100%</button><button data-action="close" aria-label="关闭原图">关闭</button></div><div class="zoom-viewport"><div class="zoom-canvas"><img class="zoom-image" alt=""></div></div>';document.body.append(dialog);
const vp=dialog.querySelector('.zoom-viewport'),img=dialog.querySelector('.zoom-image'),caption=dialog.querySelector('.zoom-caption'),level=dialog.querySelector('.zoom-level');let scale=1,origin=null,lastOverflow='',previousFocus=null;
function setScale(v){if(!origin)return;const rx=(vp.scrollLeft+vp.clientWidth/2)/Math.max(1,vp.scrollWidth),ry=(vp.scrollTop+vp.clientHeight/2)/Math.max(1,vp.scrollHeight);scale=Math.max(.1,Math.min(5,v));img.style.width=(origin.naturalWidth*scale)+'px';img.style.height='auto';level.textContent=Math.round(scale*100)+'%';vp.scrollLeft=rx*vp.scrollWidth-vp.clientWidth/2;vp.scrollTop=ry*vp.scrollHeight-vp.clientHeight/2}
function fit(){setScale(Math.min(1,(vp.clientWidth-48)/origin.naturalWidth,(vp.clientHeight-48)/origin.naturalHeight));vp.scrollLeft=0;vp.scrollTop=0}
function open(source){origin=source;previousFocus=document.activeElement;img.src=source.src;img.alt=source.alt;caption.textContent=source.alt;lastOverflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();requestAnimationFrame(fit)}
dialog.addEventListener('close',()=>{document.body.style.overflow=lastOverflow;previousFocus?.focus()});dialog.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{switch(b.dataset.action){case'close':dialog.close();break;case'in':setScale(scale*1.3);break;case'out':setScale(scale/1.3);break;case'actual':setScale(1);break;case'fit':fit();}}));vp.addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();setScale(scale*Math.exp(-e.deltaY*.006))}},{passive:false});vp.addEventListener('dblclick',()=>scale<.99?setScale(1):fit());
const pointers=new Map();let pinch=null;vp.addEventListener('pointerdown',e=>{if(e.button!==0)return;vp.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});vp.style.cursor='grabbing';if(pointers.size===2){const p=[...pointers.values()];pinch={distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),scale}}});vp.addEventListener('pointermove',e=>{const old=pointers.get(e.pointerId);if(!old)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&pinch){const p=[...pointers.values()];setScale(pinch.scale*Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)/Math.max(pinch.distance,1))}else{vp.scrollLeft-=e.clientX-old.x;vp.scrollTop-=e.clientY-old.y}});['pointerup','pointercancel'].forEach(event=>vp.addEventListener(event,e=>{pointers.delete(e.pointerId);if(pointers.size<2)pinch=null;if(!pointers.size)vp.style.cursor='grab'}));
article.querySelectorAll('img').forEach(source=>{const f=document.createElement('figure');f.className='technical-figure';const parent=source.parentElement;if(parent.tagName==='P'&&parent.childNodes.length===1){parent.replaceWith(f)}else{source.before(f)}f.append(source);source.decoding='async';const classify=()=>f.classList.toggle('portrait',source.naturalHeight>source.naturalWidth*1.15);if(source.complete)classify();else source.addEventListener('load',classify,{once:true});source.addEventListener('click',()=>open(source));const b=document.createElement('button');b.type='button';b.className='figure-open';b.textContent='放大查看';b.addEventListener('click',()=>open(source));f.append(b)});
})();
